extends:
  - '@commitlint/config-conventional'
rules:
  type-enum: [2, 'always', [
    'build',
    'docs',
    'feat',
    'fix',
    'perf',
    'refactor',
    'revert',
    'test'
  ]]
  scope-enum: [2, 'always', [
    'styleguide'
  ]]
  scope-empty: [0, 'never']
