const CAPABILITIES = [
  "Border Management",
  "Border Health Management",
  "Containment & quarantine management",
  "Immigration Screening",
  "Business Continuity Management",
  "Business Continuity Planning",
  "Recovery Management",
  "Change Management",
  "Benefits Management",
  "Change Governance",
  "Portfolio & Programme Management",
  "Chief Operating Officer",
  "Radiation, Chemical and Environmental Hazards",
  "Clinical and Science",
  "Behavioural Science",
  "Chemical Science",
  "Clinical Research",
  "Diagnostics",
  "Emerging Science Technology",
  "Environmental Science",
  "Epidemiological",
  "Immunology",
  "Microbiology Research",
  "Radiation Science",
  "Science Hub Management",
  "Serology",
  "Service Evaluation",
  "Whole genome sequencing",
  "Commercial",
  "Commercial Strategy",
  "Procurement & Contract Management",
  "Supplier Management",
  "Communication",
  "Corporate Affairs & Media Communications",
  "Emergency & External Communications",
  "Internal Communications",
  "Communications",
  "Internal & External Communications",
  "Contact Centre Data Management",
  "Contact Centre Management",
  "Contact Tracing",
  "Digital Engagement Management",
  "Operations Management",
  "Service Centre Management",
  "Corporate Affairs",
  "Corporate Functions",
  "Corporate and Governance",
  "Clinical Governance",
  "Corporate Governance",
  "Legal Advice",
  "Performance Management",
  "Quality Assurance",
  "Regulatory Compliance",
  "Research Governance",
  "Secretariat Management",
  "Customer & Channel Management",
  "Beneficiary Insight",
  "Channel Design",
  "Complaints & Queries",
  "Customer Information Management",
  "Customer Insight",
  "Customer Segmentation",
  "Data Analytics",
  "Bioinformatics & Genomics",
  "Data Engineering (inc. exploitation)",
  "Data Science",
  "Data Visualisation",
  "Official Statistics",
  "Predictive Analytics",
  "Data Operations",
  "Blood Safety, Hepatitis, Sexually Transmitted Infections Service (STIS) & HIV",
  "Healthcare Acquired Infections & Anti-Microbial Resistance",
  "Infections Research & Development",
  "Local Microbiology Laboratories & Infection Specialist Services",
  "National Immunisation",
  "National Specialist Surveillance & Reference Laboratories",
  "Rare Zoonotic Infections, Gastrointestinal Infections and Associated Areas",
  "Surveillance Systems & Bioinformatics Division",
  "Vaccines & Countermeasures",
  "Data Strategy",
  "Data Principles, Standards & Assurance",
  "Deliver Health Protection",
  "Chemical Health Protection Management",
  "Counter Measures Management",
  "Environmental Health Protection  Management",
  "Global Operations",
  "Infectious Disease Health Protection Management",
  "National Operations",
  "Radiation HP Management",
  "Regional Service Delivery",
  "Tracing",
  "Emergency Resilience",
  "Emergency Response",
  "Emergency Response / Global Engagement",
  "Pandemic Management",
  "Readiness Management",
  "Resilience Response Readiness",
  "Surge Capacity Planning",
  "Engagement Management",
  "Global Engagement",
  "Local Authority Engagement Strategy",
  "Pan Regional Engagement Strategy",
  "Parliamentary Engagement",
  "Parliamentary Engagement Strategy",
  "Public Engagement",
  "Enterprise Management",
  "Asset Management",
  "Audit Management",
  "Change Management",
  "Commercial management",
  "Demand Management",
  "Enterprise Architecture Management",
  "Architectural Governance",
  "Data Governance",
  "Estates Management",
  "Facilities Management",
  "Financial Governance",
  "Financial management",
  "Environmental, Health & Infection Monitoring",
  "Emerging Infections Monitoring",
  "Environmental Monitoring",
  "Environmental, Health & Infection Monitoring / Local Authority Engagement Strategy",
  "Estate Management",
  "Health & Safety Management",
  "Property Management",
  "Finance & Commercial",
  "Business Development",
  "Digital & Information Communication Technology (ICT)",
  "Estates & Facilities",
  "Financial Management & Financial Strategy & Services",
  "Procurement",
  "Financial Management",
  "Financial Governance",
  "Financial Operations",
  "Financial Planning",
  "Financial Reporting",
  "Governance management",
  "Health Equity Assurance",
  "Equity Monitoring Management",
  "Equity Research Management",
  "Health Improvement",
  "Alcohol, Drugs, Tobacco and Inclusion health",
  "Dental Public Health",
  "Diet, Obesity & Physical Activity",
  "Health and Justice",
  "Health Improvement Priority Programmes",
  "Health Intelligence",
  "National Disease Registration Service ",
  "National Screening Programmes, UKNSC",
  "Research, Translation & Innovation (Health Improvement)",
  "Research, Translation & Innovation (Health Protection)",
  "Screening Quality Assurance",
  "Screening Quality Improvement",
  "Sexual Health and HIV Services",
  "Health Marketing",
  "Health Marketing & Behavioural Change",
  "Health Protection & Medical",
  "Emergency Preparedness & Response (EPR)",
  "Global Public Health (Health Improvement)",
  "Global Public Health (Health Protection)",
  "Medical and Public Health Professional Leadership and Practice",
  "National Healthcare Public Health",
  "National Poisons Information Service",
  "UK Teratology Information Service",
  "Horizon Scanning & Analysis",
  "Clinical Analysis",
  "Scientific Analysis",
  "Incident Response",
  "Case & Incident Response Management",
  "Situation Management",
  "Information Management",
  "Data Creation & Management",
  "Forms and Data Collection",
  "Data Governance",
  "Data Quality Assurance",
  "Data Sharing",
  "Master Data Management",
  "Research & Development Innovation",
  "Knowledge Management",
  "Content & Asset Management",
  "Knowledge Governance",
  "Knowledge integration",
  "Lab Network Management",
  "High Throughput Lab Management",
  "Other lab management",
  "MI & Report Management",
  "Nursing, Maternity & Early Years",
  "Maternity and Early Years",
  "Nursing, Midwifery, AHP and Emergency Services Public Health Leadership",
  "Quality, Clinical Governance and Safeguarding",
  "Pandemic Response Unit",
  "Covid Response",
  "Partnership Management",
  "Devolved Administration Partnership Management",
  "Devolved Administrations Partnership Mgt",
  "Global Partnership Management",
  "Local, Regional & National Partnership Management",
  "People",
  "People Services",
  "Public Health Workforce",
  "People Management",
  "Organisation, Culture & Leadership Development",
  "Pay, Reward & Performance Management",
  "People Operations",
  "Recruitment & Sourcing",
  "Workforce Development",
  "People Strategy Management Plus",
  "Places & Regions",
  "Regional & Sub Regional Health Care Public Health (HCPH)",
  "Regional and Local Health and Wellbeing Advice and Support (DHSC)",
  "Regional and Local Health and Wellbeing Advice and Support (UKHSA)",
  "Regional and Local Health Protection",
  "Regional and Local Screening and Immunisation Commissioning Support and Expert Advice (embedded in NHSE)",
  "Policy Development",
  "Policy  Implementation",
  "Policy Definition (internal/ external policy)",
  "Policy Definition (internal/external policy)",
  "Policy Implementation",
  "Public Health Advise, Guidance & Training",
  "Advice Management",
  "Guidance Distribution",
  "Public Health Training",
  "Risk Communication",
  "Reference Data Management",
  "Research Management",
  "Evidence Review & Management",
  "Research Design",
  "Research Dissemination",
  "Research Partnerships",
  "Research Standards",
  "Risk Management",
  "Corporate Risk Management",
  "Scientific & Clinical Risk Management",
  "Science Hub",
  "Science Hub Programme",
  "Scientific Modelling",
  "Data Modelling & Analysis",
  "Security Management",
  "Cyber Security",
  "Information Security",
  "Physical Security Management",
  "Service Design & Management",
  "Customer Experience",
  "Product Management",
  "Service Design",
  "Technology Innovation",
  "Strategy",
  "Health Economics & Modelling",
  "Strategy",
  "Strategy Development",
  "Business Planning",
  "Strategy Management",
  "Supply Chain Management",
  "SCM - Delivery Management",
  "SCM - Demand Management",
  "Test Supply Chain Management",
  "Vaccine Supply Chain",
  "Surveillance Management",
  "Detect Emerging Infections",
  "Infectious Disease Surveillance",
  "Local, National & Global Health Surveillance",
  "RCE Surveillance",
  "Surveillance Design",
  "Technology Management",
  "API Ecosystem Management",
  "Application Porfolio Management",
  "Collaboration and Teamwork",
  "Identity and Access Management",
  "IT Architecture & IT Strategy",
  "IT Operations & Service Desk",
  "Network Management",
  "Platform, Infrastructure & Hosting Management",
  "Cloud Financial Management (FinOps)",
  "Container Platform Governance",
  "Virtual Desktop Infrastructure Management",
  "Voice and Telephony",
  "Software, Release & Development",
  "DevOps & Continuous Integration/Delivery",
  "Unified Device Management",
  "Test & Trace",
  "Analytics",
  "Cloud",
  "Communications",
  "Contain",
  "Data Transfer",
  "Genomics",
  "Operations",
  "Productivity",
  "Testing",
  "Tracing",
  "Utility",
  "Testing",
  "Diagnostic Testing",
  "Forensic Testing",
  "Mass Testing",
  "Point of Care Testing",
  "Rapid Testing",
  "Vaccine Testing",
  "Threat Management",
  "Global Threat Monitoring",
  "Hazard Assessment",
  "Quantify Threat",
  "Threat Assessment",
  "Vaccines Management",
  "Vaccine Development",
  "Vaccine Partnerships",
  "Vaccine Production"
]

export default CAPABILITIES;
