const CAPABILITIES = [
  "Advice Management",
  "Behavioural Science",
  "Beneficiary Insight",
  "Benefits Management",
  "Bioinformatics &amp; Genomics",
  "Border Health Management",
  "Business Continuity Planning",
  "Business Planning",
  "Case &amp; Incident Response Management",
  "Change Governance",
  "Channel Design",
  "Chemical Health Protection Management",
  "Chemical Science",
  "Clinical Analysis",
  "Clinical Governance",
  "Clinical Research",
  "Commercial Strategy",
  "Complaints &amp; Queries",
  "Contact Tracing",
  "Containment & quarantine management",
  "Content &amp; Asset Management",
  "Corporate Affairs & Media Communications",
  "Corporate Governance",
  "Corporate Risk Management",
  "Counter Measures Management",
  "Customer Experience",
  "Customer Information Management",
  "Customer Insight",
  "Customer Segmentation",
  "Cyber Security",
  "Data Creation &amp; Management",
  "Data Engineering (inc. exploitation)",
  "Data Governance",
  "Data Modelling &amp; Analysis",
  "Data Quality Assurance",
  "Data Science",
  "Data Sharing",
  "Data Visualisation",
  "Detect Emerging Infections",
  "Devolved Administration Partnership Management",
  "Devolved Administrations Partnership Mgt",
  "Diagnostic Testing",
  "Diagnostics",
  "Digital Engagement Management",
  "Emergency &amp; External Communications",
  "Emerging Infections Monitoring",
  "Emerging Science Technology",
  "Environmental Health Protection  Management",
  "Environmental Monitoring",
  "Environmental Science",
  "Epidemiological",
  "Equity Monitoring Management",
  "Equity Research Management",
  "Evidence Review &amp; Management",
  "Financial Governance",
  "Financial Operations",
  "Financial Planning",
  "Financial Reporting",
  "Forensic Testing",
  "Global Engagement",
  "Global Operations",
  "Global Partnership Management",
  "Global Threat Monitoring",
  "Guidance Distribution",
  "Hazard Assessment",
  "Health &amp; Safety Management",
  "High Throughput Lab Management",
  "Immigration Screening",
  "Immunology",
  "Infectious Disease Health Protection Management",
  "Infectious Disease Surveillance",
  "Information Security",
  "Internal Communications",
  "IT Architecture &amp; IT Strategy",
  "IT Operations &amp; Service Desk",
  "Knowledge Governance",
  "Knowledge integration",
  "Legal Advice",
  "Local Authority Engagement Strategy",
  "Local, National &amp; Global Health Surveillance",
  "Local, Regional & National Partnership Management",
  "Mass Testing",
  "Microbiology Research",
  "National Operations",
  "Official Statistics",
  "Operations Management",
  "Organisation, Culture &amp; Leadership Development",
  "Other lab management",
  "Pan Regional Engagement Strategy",
  "Pandemic Management",
  "Parliamentary Engagement",
  "Parliamentary Engagement Strategy",
  "Pay, Reward &amp; Performance Management",
  "People Operations",
  "Performance Management",
  "Physical Security Management",
  "Platform, Infrastructure &amp; Hosting Management",
  "Point of Care Testing",
  "Policy  Implementation",
  "Policy Definition (internal/external policy)",
  "Portfolio &amp; Programme Management",
  "Predictive Analytics",
  "Procurement &amp; Contract Management",
  "Product Management",
  "Property Management",
  "Public Engagement",
  "Public Health Training",
  "Quality Assurance",
  "Quantify Threat",
  "Radiation HP Management",
  "Radiation Science",
  "Rapid Testing",
  "RCE Surveillance",
  "Readiness Management",
  "Recovery Management",
  "Recruitment &amp; Sourcing",
  "Regional Service Delivery",
  "Regulatory Compliance",
  "Research &amp; Development Innovation",
  "Research Design",
  "Research Dissemination",
  "Research Governance",
  "Research Partnerships",
  "Research Standards",
  "Resilience Response Readiness",
  "Risk Communication",
  "Science Hub Management",
  "Scientific &amp; Clinical Risk Management",
  "Scientific Analysis",
  "SCM - Delivery Management",
  "SCM - Demand Management",
  "Secretariat Management",
  "Serology",
  "Service Centre Management",
  "Service Design",
  "Service Evaluation",
  "Situation Management",
  "Software, Release &amp; Development",
  "Strategy Management",
  "Supplier Management",
  "Surge Capacity Planning",
  "Surveillance Design",
  "Technology Innovation",
  "Test Supply Chain Management",
  "Threat Assessment",
  "Tracing",
  "Vaccine Development",
  "Vaccine Partnerships",
  "Vaccine Production",
  "Vaccine Supply Chain",
  "Vaccine Testing",
  "Whole genome sequencing",
  "Workforce Development"
];

export default CAPABILITIES;
